- name: Clone OPNsense VM from template
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ root_password }}"
    api_host: "localhost"
    node: "{{ hostname }}"
    name: "fog"
    clone: "template-{{ hostname }}"
    memory: 2048  # You can adjust memory, cores, and other parameters as per your needs.
    cores: 1
    sockets: 1
    state: present
    sshkeys: "{{ enso_ssh_pub }}"
  register: new_fog_vm

- name: Debug new VM details
  debug:
    var: new_fog_vm.vmid

- name: copy .fogsettings
  copy:
    src: files/.fogsettings
    dest: /tmp/.fogsettings

- name: copy setup.sh
  copy:
    src: files/setup.sh
    dest: /tmp/setup.sh

- name: Create /opt/fog directory in KVM image
  command: >
    virt-customize -a "/var/lib/vz/images/{{ new_fog_vm.vmid }}/vm-{{ new_fog_vm.vmid }}-disk-0.raw" --mkdir /opt/fog

- name: Upload .fogsettings to KVM image using virt-customize
  command: >
    virt-customize -a "/var/lib/vz/images/{{ new_fog_vm.vmid }}/vm-{{ new_fog_vm.vmid }}-disk-0.raw" --upload /tmp/.fogsettings:/opt/fog/.fogsettings

- name: Upload setup.sh to KVM image
  command: >
    virt-customize -a "/var/lib/vz/images/{{ new_fog_vm.vmid }}/vm-{{ new_fog_vm.vmid }}-disk-0.raw" --upload /tmp/setup.sh:/opt/fog/setup.sh

# - name: Execute setup.sh in KVM image
#   command: >
#     virt-customize -a "/var/lib/vz/images/{{ new_fog_vm.vmid }}/vm-{{ new_fog_vm.vmid }}-disk-0.raw" --run-command 'chmod +x /opt/fog/setup.sh' --run-command '/opt/fog/setup.sh'
#   register: command_output  # Register the output into a variable

# - name: Show command output
#   debug:
#     msg: "{{ command_output.stdout_lines }}"  # Print the standard output lines


- name: Start VM using qm command
  ansible.builtin.command:
    cmd: "qm start {{ result.vmid }}"

- name: Wait for QEMU Guest Agent to respond
  ansible.builtin.command:
    cmd: "qm guest exec {{ result.vmid }} -- bash -c 'cd /tmp/fogproject-master/bin/; /bin/bash installfog.sh -Y'"
  register: qemu_agent_status
  until: qemu_agent_status.rc == 0
  retries: 30  # Number of retries before giving up; adjust as needed
  delay: 10  # Delay in seconds between retries; adjust as needed

